### ISSUE TITLE
"Unresolved dependencies" warning when importing declaration from `node_modules`

### ISSUE THREAD

**Issue by Kinco4TC** [ezolenko/rollup-plugin-typescript2#288] opened 2021-10-25 07:52 UTC
#### What happens and why it is wrong
When I import a type from node_modules,  as code is 
```ts
// index.d.ts
import { EventType } from 'rrweb/typings/types';

// rrweb/typings/types.d.ts
export declare enum EventType {
    DomContentLoaded = 0,
    Load = 1,
    FullSnapshot = 2,
    IncrementalSnapshot = 3,
    Meta = 4,
    Custom = 5,
    Plugin = 6
}
```
rollup warn me that 
```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
rrweb/typings/types (imported by src/types/index.ts)
```
and the compile file is
```js
// dist/index.esm.js
// ...
import { EventType } from 'rrweb/typings/types';
// ...
```

**But If I declare local, it compile success!!!**
##### Versions

```text

```

#### rollup.config.js

<details>
  <summary>`rollup.config.js`: </summary>

```js
  export default [
  {
    input: 'src/index.ts',
    output: [
      {
        file: 'dist/index.esm.js',
        format: 'esm',
      },
      {
        file: 'dist/index.js',
        format: 'cjs',
      },
    ],
    plugins: [
      babel({
        exclude: ['node_modules/**'],
        runtimeHelpers: true,
      }),
      commonjs({
        browser: true,
      }),
      resolve({
        mainFields: ['jsnext', 'preferBuiltins', 'browser'],
        preferBuiltins: false,
      }),
      re({
        patterns: [
          {
            match: /types\.ts$/,
            test: /util\.emptyArray/,
            replace: 'Object.freeze ? Object.freeze([]) : []',
          },
        ],
      }),
      webWorkerLoader({
        targetPlatform: 'browser',
        extensions: ['.js', '.ts'],
      }),
      typescript({
        typescript: require('typescript'),
      }),
    ],
  },
];
```

</details>

#### tsconfig.json

<details>
  <summary>`tsconfig.json`: </summary>

```json5
{
  // see https://www.typescriptlang.org/tsconfig to better understand tsconfigs
  "include": ["src"],
  "compilerOptions": {
    "importHelpers": true,
    // output .d.ts declaration files for consumers
    "declaration": true,
    // output .js.map sourcemap files for consumers
    // "sourceMap": true,
    // match output dir to input dir. e.g. dist/index instead of dist/src/index
    "rootDir": "src",
    // stricter type-checking for `stronger correctness. Recommended by TS
    "strict": false,
    // linter checks for common issues
    "noImplicitReturns": false,
    "noFallthroughCasesInSwitch": true,
    // noUnused* overlap with @typescript-eslint/no-unused-vars, can disable if duplicative
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    // use Node's module resolution algorithm, instead of the legacy TS one
    "moduleResolution": "node",
    // interop between ESM and CJS modules. Recommended by TS
    "esModuleInterop": true,
    // significant perf increase by skipping checking .d.ts files, particularly those in node_modules. Recommended by TS
    "skipLibCheck": true,
    // error out if import and file system have a casing mismatch. Recommended by TS
    "forceConsistentCasingInFileNames": true,
    // `tsdx build` ignores this option, but it is commonly used when type-checking separately with `tsc`
    "noEmit": true,
    "allowUnreachableCode": true, 
    "allowUnusedLabels": false,
    "alwaysStrict": false,
    "preserveConstEnums": true, 
    "experimentalDecorators": true, 
    "sourceMap": false,
    "resolveJsonModule": true,
    "noImplicitAny": true,
    "removeComments": true,
    "types": ["node"],
    "target": "es5", 
    "module": "ES2015", 
    "allowJs": true, 
    "jsx": "react",
    "allowSyntheticDefaultImports": true,
    "lib": ["es5", "es7", "dom"],
    "baseUrl": ".",
    "paths": {
      "*": ["src/*", "src/types/*"]
    }
  }
}
```

</details>

#### package.json

<details>
  <summary>`package.json`: </summary>

```json
{
  "name": "******",
  "type": "module",
  "module": "dist/index.esm.js",
  "author": "******",
  "version": "0.1.0",
  "license": "ISC",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "files": [
    "src"
  ],
  "engines": {
    "node": ">=10"
  },
  "scripts": {
    "build": "rollup -c",
    "dev": "rollup -c --watch"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.{js,jsx,ts,tsx}": "yarn run lint:fix"
  },
  "devDependencies": {
    "@babel/preset-env": "^7.15.8",
    "@rollup/plugin-commonjs": "^21.0.0",
    "@rollup/plugin-json": "^4.1.0",
    "@size-limit/preset-small-lib": "^5.0.3",
    "@typescript-eslint/eslint-plugin": "^4.10.0",
    "@typescript-eslint/parser": "^4.10.0",
    "eslint": "^7.15.0",
    "eslint-config-prettier": "^7.0.0",
    "eslint-plugin-prettier": "^3.3.0",
    "eslint-plugin-react": "^7.21.5",
    "husky": "^7.0.2",
    "lint-staged": "^11.2.3",
    "prettier": "^2.2.1",
    "prettier-eslint": "^13.0.0",
    "pretty-quick": "^3.1.1",
    "rollup": "^2.58.0",
    "rollup-plugin-babel": "^4.4.0",
    "rollup-plugin-node-resolve": "^5.2.0",
    "rollup-plugin-postcss": "^4.0.1",
    "rollup-plugin-re": "^1.0.7",
    "rollup-plugin-typescript2": "^0.30.0",
    "rollup-plugin-web-worker-loader": "^1.6.1",
    "size-limit": "^5.0.3",
    "tslib": "^2.3.1",
    "typescript": "^4.4.3"
  },
  "dependencies": {
    "@babel/core": "^7.15.8",
    "rrweb": "^1.0.4",
  }
}
```

</details>

#### plugin output with verbosity 3

<details>
  <summary>plugin output with verbosity 3: </summary>

</details>

**Comment by agilgur5** [comment] 2022-05-01 21:13
> rollup warn me that

So the warning being referenced here is just a warning, and per [the link it outputs](https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency), the warning can be disabled by using an explicit `externals` configuration in your `rollup.config.js`. It's also a warning from Rollup, not this plugin.

> **But If I declare local, it compile success!!!**

Based on this statement, it sounds like you might be getting a different error afterward? No `verbosity: 3` log was attached, so I can't tell exactly.

That being said, it sounds like a potential duplicate of #273 -- declaration files aren't supposed to be directly imported in TS and that is `tsc` behavior as well.

But it's also not clear, it seems you might be authoring a declaration file (`.d.ts`) directly instead of a TS file? This plugin doesn't process declaration files, so that could be a separate issue too. Would need a reproduction and some clarification to understand what you're trying to achieve and whether this is actually a bug or not.

**Closed by agilgur5** 2022-05-01 21:13 UTC
Labels: solution: tsc behavior, kind: support, solution: out-of-scope
