### ISSUE TITLE
definition files are not generated

### ISSUE THREAD

**Issue by baad** [ezolenko/rollup-plugin-typescript2#19] opened 2017-05-31 19:20 UTC
I could  not generate  *.d.ts files using rollup-plugin-typescript2.   I set declaration flag to true in tsconfig.json. The documentation of plugin says it must work however it did not. 
```
{
    "compilerOptions": {
        "typeRoots": ["node_modules/@types"],
        "types": ["jquery", "angular", "lodash", "jasmine", "angular-mocks"],
        "allowUnreachableCode": false,
        "allowUnusedLabels": false,
        "baseUrl": "./src",
        "forceConsistentCasingInFileNames": true,
        "module": "commonjs",
        "moduleResolution": "node",
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "preserveConstEnums": false,
        "target": "es5",
        "sourceMap": false,
        "declaration": true
    },
    "include": [
        "src/module.ts",
        "src/**/*.ts"
    ],
    "exclude": [
        "src/test/*.ts"
    ]
}

```
Any help would be much appreciated

**Comment by ezolenko** [comment] 2017-05-31 19:53
Could you double check that you are using v0.4.2 from npm?

There is also `declarationDir` option that lets you set output path for .d.ts, by default they are dropped besides corresponding .ts files.

**Comment by baad** [comment] 2017-05-31 20:03
Thanks for quick reply. I upgraded to latest version 0,4,2 from 0.4.1. Still it does not work.
I set the declarationDir  too.  

Will the .d.ts files be bundled too or do we need to somethign else for it?

**Comment by ezolenko** [comment] 2017-05-31 20:27
You can look at this plugin itself -- I set declaration dir to be the same as rollup output dir and typescript drops d.ts files besides rollup output -- look in `dist` folder. (I haven't verified exactly how useful that is for npm package though :))

They are not bundled, just generated.

What's your typescript version? Could you set `verbosity` to 3 and attach the output?

**Comment by ezolenko** [comment] 2017-06-22 21:27
Closing this for now, let me know if still broken.

**Closed by ezolenko** 2017-06-22 21:27 UTC

**Comment by JackieManuja** [comment] 2018-02-22 11:05
tsconfig
`{
    "compilerOptions": {
      "target": "es5",
      "module": "commonjs",
      "moduleResolution": "node",
      "strict": true,
      "jsx": "react",
      "declaration": true, 
      "declarationDir": "/type",
      "allowSyntheticDefaultImports": true,
    } 
  }`
Rollup config

`input:'./tmp/coe/core/Hello.tsx',
      output: {         
        format: 'es',
        sourcemap: true       
      },
      plugins: [        
        typescript({            
            tsconfig: "./tmp/coe/core/tsconfig.json",
            verbosity: 3,
            cacheRoot: './build_cache' 
        })
      ],
      external: ['react']`

Still decleration files are not generated

Can anyone help?

**Comment by agilgur5** [comment] 2022-05-26 16:51
OP never responded with more info and no repro was ever provided.

This plugin has evolved pretty significantly since then, so if you're experiencing a similar issue, please open a new issue and provide a reproduction for debugging purposes.
It is typically easier for maintainers to track that way as opposed to comments on old issues that may even have similar errors but different root causes.

Locking as such
