### ISSUE TITLE
Declarations broken under Vite when upgrading `plugin-vue` to 1.8

### ISSUE THREAD

**Issue by mseele** [ezolenko/rollup-plugin-typescript2#285] opened 2021-10-08 05:42 UTC
#### What happens and why it is wrong

After updateing **@vitejs/plugin-vue** version typescript generation via **rollup-plugin-typescript2** is broken.
Using version 1.7.1 of @vitejs/plugin-vue the generation via rollup-plugin-typescript2 works like expected.

_From version 1.8.0 it does not longer generate type definitions for components but list them in the index.d.ts file._

#### Reproduction
- Checkout https://github.com/mseele/vite-typescript2-output-broken, run `yarn install` and then `yarn build`
- In the dist directory a **index.d.ts** file will be generated with the reference to **./components/Hello.vue**
- The **./components/Hello.vue.d.ts** file will **not** be generated
- Change `@vitejs/plugin-vue` in package.json to `1.7.1`, run `yarn install` and then `yarn build` again
- Everything works as expected: the missing **./components/Hello.vue.d.ts** file has been generated

#### See also

Please see https://github.com/vitejs/vite/issues/5044 i've opened in vite repo

**Comment by zeusdeux** [comment] 2021-11-03 14:32
Would the ordering make a difference, i.e., moving rpt2 above vue? I'd think vue is stripping away types before source is fed to rpt2

**Comment by agilgur5** [comment] 2022-04-24 16:15
Reading this issue and the one in Vite, as well as its linked issues, it sounds very much like a regression in Vite with the root cause already found there.

Will be closing this as out-of-scope then, but let us know if this needs reopening down the line if contraindicating info pops up.

**Closed by agilgur5** 2022-04-24 16:15 UTC
Labels: scope: integration

**Comment by agilgur5** [comment] 2022-07-30 17:15
Per the upstream issue, seems like this was fixed in https://github.com/vitejs/vite/pull/7909 and released in `@vitejs/plugin-vue` [`v3.0.0-alpha.0`](https://github.com/vitejs/vite/blob/main/packages/plugin-vue/CHANGELOG.md#300-alpha0-2022-05-13)
