### ISSUE TITLE
Declaration file output settings not compatible with the latest Rollup

### ISSUE THREAD

**Issue by ericwgreene** [ezolenko/rollup-plugin-typescript2#30] opened 2017-08-24 18:23 UTC
If output declaration files are desired, this version of the plugin will not work with Rollup after 0.47.6. Version 0.47.6 of Rollup works, but future versions do not.

This is because the Rollup **dest** option was changed to **output.file** which this plugin does not read when determining the declaration file  paths.

https://github.com/rollup/rollup/issues/1479

The plugin code in **index.ts** needs to be changed from

`
onwrite({ dest }: IRollupOptions)
`
to

`
onwrite({ file: dest }: IRollupOptions)
`

then it should work. Or something similar to this.

**Comment by ezolenko** [comment] 2017-08-24 18:56
I'll check it out, thanks.

**Comment by Havunen** [comment] 2017-08-25 12:02
InfernoJS project hit this same bug and root cause seems to be the same. any ETA for fix?

**Comment by Havunen** [comment] 2017-08-25 12:04
Here is gist about changes made to rollup written by Rich Harris https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32

**Comment by ezolenko** [comment] 2017-08-25 17:17
Yep, I have a fix (should work for old and new rollup), will make a new release today or tomorrow.

**Comment by ericwgreene** [comment] 2017-08-25 17:18
You rock! Thanks!

**Comment by ezolenko** [comment] 2017-08-26 04:23
Ok, should be fixed in 0.5.2

**Closed by ezolenko** 2017-08-26 04:23 UTC
