### ISSUE TITLE
Fails with complex usage scenario

### ISSUE THREAD

**Issue by TimMensch** [ezolenko/rollup-plugin-typescript2#2] opened 2017-02-28 19:06 UTC
Apologies for not breaking this down to a minimal reproduction case, but I don't have time right now and I thought you might be interested in the issue even without the full repro, and that you might understand what the fundamental issue is.

I have a pretty complex Rollup configuration:

```
module.exports = {
    entry: 'src/host/main.ts',
    dest: 'int/js/mainout.js',
    exports: "none",
    external: [
        "bluebird",
        "power-assert"
    ],
    globals: {
        "bluebird": "Promise",
        "power-assert": "assert"
    },
    useStrict: true,
    sourceMap: true,
    format: "iife",
    plugins: [
        json(),
        typescript({
            typescript: require('typescript'),
        }),
        nodeResolve({
            // use "jsnext:main" if possible
            // – see https://github.com/rollup/rollup/wiki/jsnext:main
            jsnext: true, // Default: false

            // use "main" field or index.js, even if it's not an ES6 module
            // (needs to be converted from CommonJS to ES6
            // – see https://github.com/rollup/rollup-plugin-commonjs
            main: true, // Default: true

            // if there's something your bundle requires that you DON'T
            // want to include, add it to 'skip'
            skip: [],  // Default: []

            // some package.json files have a `browser` field which
            // specifies alternative files to load for people bundling
            // for the browser. If that's you, use this option, otherwise
            // pkg.browser will be ignored
            browser: true, // Default: false

            // not all files you want to resolve are .js files
            extensions: [ '.js', '.json', '.ts' ], // Default: ['.js']
            sourceMap: true,

            // whether to prefer built-in modules (e.g. `fs`, `path`) or
            // local ones with the same names
            preferBuiltins: false // Default: true
        }),
        commonjs({
            extensions: [ '.js', '.ts' ],
            namedExports: {
                "javascript-astar": [ "Graph", "astar" ],
                "screenfull": [ "request" ],
                "marked": ["Renderer","setOptions","parse"],
            }
        }),
        buble({transforms: { dangerousForOf: true, dangerousTaggedTemplateString: true }})
    ]
};
```

This (mostly) works with the rollup-plugin-typescript plugin, but I thought I'd try this variant of the plugin instead. In part I wanted to try this because the last step above -- buble -- is not processing the TypeScript helpers injected by rollup-plugin-typescript. Since you're doing something different, I thought that issue might be solved by switchign to this plugin.

But when I switch my include to rollup-plugin-typescript2, I get an error:

```
Failed to build client-js: Error: Module C:/Users/tim/projects/games/steel/node_modules/javascript-astar/astar.js does not export astar (imported by C:/Users/tim/projects/games/steel/src/common/pathhelper.ts)
    at Module.trace (C:\Users\tim\projects\games\steel\node_modules\rollup\dist\rollup.js:6432:29)
    at C:\Users\tim\projects\games\steel\node_modules\rollup\dist\rollup.js:6006:32
...
```

This doesn't even look like it's in your code, but it doesn't happen when I run the code through the older plugin, and I don't have the time to dig down to the root cause here, so I need to fall back on the older plugin. Looking at the TypeScript options you're setting:

```
noEmitHelpers: true
importHelpers: true
```

... I thought one of these might be causing the problem, but no, when I set those it works using the old plugin. Not only that, but it fixes the problem I was having (because TypeScript is now using the imported helpers which buble correctly).

I have a TypeScript declaration file for javascript-astar, but honestly what it looks like is happening above is not a TypeScript bug but some kind of interaction problem between this plugin and the commonjs plugin (where I specify explicit exports for javascript-astar).

So if I were you and wanted to test this, I'd get an example together that imports some raw JavaScript using the node-resolve and commonjs plugins and see how rollup-plugin-typescript2 might be breaking commonjs.

**Comment by ezolenko** [comment] 2017-02-28 20:41
Hm, I use noderesolve and commonjs in my own project and it does import some pure js libs...

```
       rollupTypescript({ clean: false, check: true, cacheRoot: "./.cache", verbosity: 2 }),
       rollupNodeResolve({ jsnext: true, main: true }),
       rollupCommonjs({ ignoreGlobal: true, include: "node_modules/**" }),
```

Could you post how exactly you are importing `javascript-astar` in `pathhelper.ts`?

This is how mine are imported:
```
import * as SourceMap from "source-map";
import screepsProfiler from "screeps-profiler";
```

I remember rewriting imports from require() when switching to this plugin, but not sure if that was due to a similar errors.

BTW, why to you let commonjs and nodeResolve process .ts files?

**Comment by TimMensch** [comment] 2017-02-28 21:56
```
import { astar, Graph } from "javascript-astar";
```

This feels like the standard `rollup-plugin-commonjs` error where the plugin doesn't know what a file exports (it runs heuristics on the JavaScript to guess, but can't always get it right), and the entries in `namedExports` are there to work around that limitation. 

So I think that however `rollup-plugin-commonjs` identifies an import, it's no longer recognizing `javascript-astar` as the correct name for that module, so the `namedExports` end up broken.

> BTW, why to you let commonjs and nodeResolve process .ts files?

Good question! I honestly don't remember exactly when or why I included those. I suspect I thought it was necessary and never questioned it. Maybe I imagined that some Node packages might contain TypeScript that I could import directly? 

But now I've deleted the `*.ts` references from the config. A rebuild of everything finds it all byte-identical, so those were clearly unneeded. Thanks for pointing that out.

**Comment by ezolenko** [comment] 2017-03-02 05:24
Can't reproduce with:
```
"rollup-plugin-commonjs": "^7.0.0",
"rollup-plugin-node-resolve": "^2.0.0",
"rollup-plugin-typescript2": "^0.1.2",
"rollup": "^0.41.4",
"typescript": "^2.1.6",
"@types/javascript-astar": "0.0.28",
"javascript-astar": "0.4.1",
```

namedExports seem to be working for me -- I get `does not export astar` when I remove it and error goes away (and gets compiled correctly) when I add namedExports back. I don't use bubble and I don't have any other name export though.

Bigger issue here is the way that package is typed (ambient declarations instead of a module) -- I couldn't find a good way to import it so that typings actually works in IDE...

**Comment by TimMensch** [comment] 2017-03-02 18:52
Sorry, I didn't give all the info. Assume it was a more general issue. 

I found issues with the standard types as well, and we've added more code, so I'm not using the standard `javascipt-astar`, nor the standard types. I'm using [TimMensch/javascript-astar](https://github.com/TimMensch/javascript-astar/), and here are my type declarations:

```
// Type definitions for javascript-astar
// Project: https://github.com/bgrins/javascript-astar
// Definitions by: brian ridley <https://github.com/ptlis/>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

declare interface GridNode {
    x: number;
    y: number;
    weight: number; // The cost to go to step onto this tile
    g: number; // When part of a path, this is the total weight up to this point
}

interface Heuristic {
    (pos0: { x: number, y: number }, pos1: { x: number, y: number }): number;
}

interface Heuristics {
    manhatten: Heuristic;
    diagonal: Heuristic;
    hexagonal: Heuristic;
}

declare module "javascript-astar" {
    export class Graph {
        grid: Array<Array<GridNode>>;
        constructor(grid: Array<Array<number>>, options?: { diagonal?: boolean });
    }

    export namespace astar {
        function getClosestMatchingPoint(
            graph: Graph,
            start: { x: number, y: number },
            conditions : (cPoint : GridNode) => boolean,
        ): Array<GridNode>;

        function getPathToTargetPoint(
            graph: Graph,
            start: { x: number, y: number },
            end: { x: number, y: number },
        ): Array<GridNode>;

        var heuristics: Heuristics;
    }
}
```

**Comment by ezolenko** [comment] 2017-03-05 20:51
Still can't reproduce with your fork of astar and your type definitions (copied over whatever is in @types) and most other plugin and rollup params...

Could you post your `tsconfig.json` as well?

**Comment by TimMensch** [comment] 2017-03-05 20:58
Sure, here's my tsconfig.json:

```
{
    "compilerOptions": {
        "target": "es2015",
        "module": "es2015",
        "traceResolution": false,
        "moduleResolution": "node",
        "isolatedModules": false,
        "jsx": "react",
        "allowSyntheticDefaultImports": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "skipDefaultLibCheck": true,
        "declaration": false,
        "noImplicitAny": true,
        "noImplicitUseStrict": false,
        "removeComments": false,
        "noEmitHelpers": true,
        "importHelpers": true,
        "noLib": false,
        "newLine":"LF",
        "forceConsistentCasingInFileNames": true,
        "noImplicitReturns": true,
        "sourceMap": true,
        "preserveConstEnums": true,
        "suppressImplicitAnyIndexErrors": true,
        "outDir": "int/js",
        "rootDir": "./"
    },
    "exclude": [
        "node_modules",
        "frameworks",
        "sourceArt",
        "int",
        "hostdist",
        "clientdist"
    ],
    "typeRoots": [
        "./node_modules/@types",
        "./node_modules",
        "./src/declarations"
    ],
    "compileOnSave": true,
    "buildOnSave": false,
    "atom": {
        "rewriteTsconfig": false
    }
}
```

Thanks for looking into this.

**Comment by TimMensch** [comment] 2017-03-05 21:03
It occurs to me that the actual call to a member of astar might be important?

I have:

```
    import { astar, Graph } from "javascript-astar";
// ...
    const graph = new Graph(grid);
    const path = astar.getClosestMatchingPoint(graph, start, conditionPredicate)
```

You could probably substitute "null" for missing parameters and it will still trigger Rollup to include the files/functions in the same way? Not sure if it matters.

**Comment by ezolenko** [comment] 2017-03-05 21:50
Hm, nope. Still works for me. I just log them to force the imports: `console.log(astar, Graph);`

Could you run the plugin with `verbosity: 3` and post the output up to the rollup error?

**Comment by TimMensch** [comment] 2017-03-06 00:06
Curious. I got this:
```
$ gulp client-js
[16:43:36] Using gulpfile ~\projects\games\Steel\gulpfile.js
[16:43:36] Starting 'client-js'...
Failed to build client-js: { [TypeError: Error transforming C:\Users\tim-m\projects\games\Steel\src\client\main.ts: this.context.warn is not a function]
  rollupTransform: true,
  id: '...\\games\\Steel\\src\\client\\main.ts',
  plugin: undefined }
[16:43:36] 'client-js' errored after 16 ms
[16:43:36] Error: Failed to build client-js
    at ...\games\Steel\gulpfile.js:286:19
    at process._tickCallback (node.js:369:9)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3
```

This made me think that my Rollup version wasn't new enough (I use `yarn` so things don't randomly break on me). So I bumped Rollup to latest, and then got over 800 lines of output. I used an [expiring paste bin](https://ghostbin.com/paste/ref5r) to save the full log. Yes, I removed my user name from the paste, but it's a lot of logs generated locally and I'd rather they just disappear after a couple of weeks. 😃 

As you can tell by the paths, I'm on Windows, so I guess that should be considered a possible failure trigger. The newer Rollup didn't break anything, so I'll keep it. For my other plugins, here are some versions of them and their immediate dependencies from my yarn file:

```
rollup-plugin-commonjs@^6.0.0:
  version "6.0.0"
rollup-plugin-node-resolve@^2.0.0:
  version "2.0.0"
browser-resolve@^1.11.0:
  version "1.11.2"
builtin-modules@^1.0.0, builtin-modules@^1.1.0:
  version "1.1.1"
resolve@1.1.7, resolve@^1.1.6, resolve@^1.1.7:
  version "1.1.7"
acorn@4.X, acorn@^4.0.0, acorn@^4.0.1:
  version "4.0.3"
estree-walker@^0.3.0:
  version "0.3.0"
magic-string@^0.19.0:
  version "0.19.0"
```

**Comment by TimMensch** [comment] 2017-03-06 00:26
Just in case, I decided to bump rollup-plugin-commonjs to 7.x. It produced a warning I'd never seen before, but otherwise worked in rollup-plugin-typescript, and failed mostly identically in rollup-plugin-typescript2.

```
Failed to build client-js: { [Error: 'Graph' is not exported by node_modules\javascript-astar\astar.js]
  code: 'MISSING_EXPORT',
  url: 'https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module',
  pos: 71,
  loc:
   { file: 'C:/Users/.../projects/games/Steel/src/common/pathhelper.ts',
     line: 2,
     column: 16 },
  frame: '1: import { ASTAR_GRID_OFFSET } from "../qc/hexgamemap";\r\n2: import { astar, Graph } from "javascript-astar";\r\n
                ^\n3: import { point, pAdd } from "../qc/point";\r\n4: /**\r' }
[17:23:00] 'client-js' errored after 4.05 s
[17:23:00] Error: Failed to build client-js
    at C:\Users\...\projects\games\Steel\gulpfile.js:290:19
    at process._tickCallback (node.js:369:9)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3
```

**Comment by ezolenko** [comment] 2017-03-06 06:41
Well, it is not windows, I'm testing everything on win10 too...

I was running all tests on rollup-plugin-commonjs 7.0.0 so far.

I updated debug output to include cache paths -- you should see something like this
```
rpt2: transpiling 'C:/Users/.../projects/games/Steel/src/common/pathhelper.ts'
rpt2:     cache: './.cache/f5f9d3db273836175b5d0fa2411a914499210a28/code/cache/659cac50bb87d15caa0d311983e3a3d6464250a6'
```

From cache file (it's a json) you should be able to see what ts turned your file into, although from the error message you posted I already see it didn't touch that import statement at all...

One thing to try would be to hide `pathhelper.ts`, drop `pathhelper.js` with transpiled code into its place and see if commonjs plugin handles it better this way .

You can also get `pathhelper.js` by running `tsc`. Comparing that to the plugin cache might be interesting.

**Comment by TimMensch** [comment] 2017-03-06 18:13
OK, I think you're looking in the wrong place, and I think that it IS a Windows path issue. Somehow a path is getting coerced from backslashes to forward slashes. It has nothing to do with pathhelper.ts itself, or how it's being transpiled; as you point out, the relevant import line is correct.

Unless it has to do with the rollup-plugin-json somehow, I'm not sure why it happens on my end but not on yours, but I did a bit of digging to try to narrow down the issue.

I just put some console.log statements in `rollup-plugin-commonjs.cjs.js` to see what the heck is going on. Here's what I found:

Around line 612, in the `.then()` callback of the entryModuleIdPromise, I added:

```
                console.log("entryModuleIdPromise", customNamedExports);
```

Around line 166, at the top of the `transformCommonjs` function, I put the following:

```
    console.log("transformCommonjs", id, customNamedExports);
```

And the relevant result:

```
entryModuleIdPromise { 'C:\Users\...\projects\games\Steel\node_modules\javascript-astar\astar.js': [ 'Graph', 'astar' ],
  'C:\Users\...\projects\games\Steel\node_modules\screenfull\dist\screenfull.js': [ 'request' ],
  'C:\Users\...\projects\games\Steel\node_modules\marked\lib\marked.js': [ 'Renderer', 'setOptions', 'parse' ] }
transformCommonjs C:/Users/.../projects/games/Steel/node_modules/javascript-astar/astar.js undefined
```

So somewhere, for some reason, the path is getting changed from backslashes to forward slashes, and the lookup for the astar module is being broken.

So I think my intuition was right on both counts: It has to do with Windows, *and* it has to do with the lookup in `rollup-plugin-commonjs` being broken. I don't really know why, and I need to get back to my day job.

**Comment by TimMensch** [comment] 2017-03-06 18:31
OK, I think you're looking in the wrong place, and I think that it IS a Windows path issue. Somehow a path is getting coerced from backslashes to forward slashes.

I just put some console.log statements in `rollup-plugin-commonjs.cjs.js` to see what the heck is going on. Here's what I found:

Around line 612, in the `.then()` callback of the entryModuleIdPromise, I added:

```
                console.log("entryModuleIdPromise", customNamedExports);
```

Around line 166, at the top of the `transformCommonjs` function, I put the following:

```
    console.log("transformCommonjs", id, customNamedExports);
```

And the relevant result:

```
entryModuleIdPromise { 'C:\Users\...\projects\games\Steel\node_modules\javascript-astar\astar.js': [ 'Graph', 'astar' ],
  'C:\Users\...\projects\games\Steel\node_modules\screenfull\dist\screenfull.js': [ 'request' ],
  'C:\Users\...\projects\games\Steel\node_modules\marked\lib\marked.js': [ 'Renderer', 'setOptions', 'parse' ] }
transformCommonjs C:/Users/.../projects/games/Steel/node_modules/javascript-astar/astar.js undefined
```

So somewhere, for some reason, the path is getting changed from backslashes to forward slashes, and the lookup for the astar module is being broken.

So I think my intuition was right on both counts: It has to do with Windows, and it has to do with the lookup in `rollup-plugin-commonjs` being broken. 

Now in my gulpfile, I tend to use paths with forward slashes, and that may be the relevant difference. For instance I do this:

```
const fullpath = require('path');
const path = fullpath.posix;
```

...and I only use "fullpath" when I need a "C:\" style absolute path. Otherwise I do my path.join() with the POSIX version. Here's an excerpt of my gulpfile that shows how `client-js` is built:

```
var clientCache;
gulp.task('client-js', function () {
    var options = extend({}, rollupConfig);
    options.dest = path.join(paths.client, 'js/main.js');
    options.entry = 'src/client/main.ts';
    options.cache = clientCache;
    addVendor(options);

    return rollup(options).then(
        function (bundle) {
            clientCache = bundle;
            return bundle.write(options);
        })
        .catch(err => {
            console.error("Failed to build client-js:", err);
            throw new Error("Failed to build client-js");
        });

});
```

The rollupConfig is the loaded Rollup configuration that I already showed you. You can ignore the addVendor() line; it adds a bunch of references to `options.globals` and `options.external` that aren't relevant to this bug. `paths.client` is "./server/clientdist". 

Not sure what else to suggest for reproducing the issue, but it clearly is a path issue.

**Comment by ezolenko** [comment] 2017-03-07 04:54
Yeah, you are right... Plugin uses typescript resolver and that returns posix paths.

For some reason I can't make my own build resolve astar.js, but I do see other js imports getting the treatment. 

Not quite sure what's the correct fix (or whether to fix this or the other plugin), and why old ts plugin didn't have this problem -- it also uses ts resolver...

I added a hack to pass resolved name through the same resolver commonjs plugin uses, this turns posix  path native and should match what commonjs gets when it builds the map.

Could you try master branch (`npm install "git+https://git@github.com/ezolenko/rollup-plugin-typescript2.git"`) and pass `rollupCommonJSResolveHack: true` in options?

**Comment by TimMensch** [comment] 2017-03-09 19:28
OK, grabbed master and now I get this:

```
$ gulp client-js
[12:26:27] Using gulpfile ~\projects\games\Steel\gulpfile.js
[12:26:27] Starting 'client-js'...
rpt2: import tree has cycles
[12:26:28] Finished 'client-js' after 1.26 s
```

But at least it seems to work. 🤷. Maybe that warning is a hint as to why things are different?

**Comment by ezolenko** [comment] 2017-03-10 04:09
That warning means there are cycles in import tree, not necessarily dependency cycles (not sure how useful the warning is, since modules can import and export multiple things and not all at once). So it is probably unrelated. I have it in my own code too for what its worth.

This looks like it could best be fixed in commonjs itself. I opened <https://github.com/rollup/rollup-plugin-commonjs/issues/177> and left the hack turned off by default for now. In 0.2.2 now. 

Thanks for figuring it out. :)

**Closed by ezolenko** 2017-03-10 04:09 UTC
