### ISSUE TITLE
 syntax error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.

### ISSUE THREAD

**Issue by xsweb** [ezolenko/rollup-plugin-typescript2#247] opened 2020-10-20 09:46 UTC
Fail
```ts
constructor（）{// ......
...
}
```
OK
```ts
constructor（）{
// ......
...
}
```

**Comment by ezolenko** [comment] 2020-10-20 23:15
Looks like typescript error? Does it happen when you run that file through tsc directly?

**Comment by xsweb** [comment] 2020-10-21 05:45
This error is caused by comments that do not wrap ，No error will be reported when running in cli，I want to know how to ignore the error of comment line wrapping；thx

**Comment by agilgur5** [comment] 2022-06-08 23:03
I created a minimal reproduction [here](https://stackblitz.com/edit/rpt2-issue-247?file=src/index.ts) and was unable to reproduce this error.

Neither `tsc` nor rpt2 give an error on either code sample in their latest versions (`4.7.3` for TS, `0.32.1` for rpt2).

So the error you're getting is likely due to a problem in your environment, and not a bug in rpt2.

The issue template was removed here and no log, configs, versions etc were provided, so there isn't more to try or investigate other than that. If you can produce a minimal repro, we can re-open this issue, otherwise closing as not reproducible.

**Closed by agilgur5** 2022-06-08 23:03 UTC
Labels: problem: needs more info, problem: removed issue template
